# For help with configuration see https://github.com/rszyma/kanata-tray/blob/main/README.md#configuration
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

[general]
allow_concurrent_presets = false
control_server_enable = false
control_server_port = 8100

[defaults]
tcp_port = 5829
autorestart_on_crash = false

[defaults.hooks]
# Hooks allow running custom commands on specific events (e.g. when starting preset).
# Documentation: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[defaults.layer_icons]
base = 'base.png'
mouse = 'mouse.png'
arrows = 'arrows.png'
num = 'num.png'
wm = 'wm.png'
gaming = 'gaming.png'
media = 'media.png'


[presets.'Default Preset']
kanata_executable = ''
kanata_config = '~/.config/kanata-tray/kanata.kbd'
autorun = true
